import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { deletePoll, getMyPolls, getPollReport } from '../api/polls';
import useAuth from '../hooks/useAuth';
import CreatorSidebar from '../components/CreatorSidebar';

function ShareDialog({ poll, onClose }) {
  const [copied, setCopied] = useState(false);
  const url = `${window.location.origin}/vote/${poll.id}`;
  const copy = async () => { await navigator.clipboard.writeText(url); setCopied(true); setTimeout(() => setCopied(false), 1400); };
  const share = async () => { if (navigator.share) { try { await navigator.share({ title: 'LivePoll poll', text: poll.question, url }); return; } catch {} } await copy(); };
  return <div className="modal-backdrop" role="presentation" onClick={onClose}><div className="share-modal card-surface" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={onClose}>Close</button><span className="eyebrow">SHARE POLL</span><h2>{poll.question}</h2><p className="poll-id-line">Poll ID: {poll.id}</p><div className="share-link">{url}</div><div className="share-actions"><button className="button" type="button" onClick={copy}>{copied ? 'Link copied!' : 'Copy Link'}</button><button className="small-action" type="button" onClick={() => window.open(`https://wa.me/?text=${encodeURIComponent(`${poll.question} ${url}`)}`, '_blank')}>WhatsApp</button><button className="small-action" type="button" onClick={share}>Native Share</button></div></div></div>;
}

function DeleteDialog({ poll, onCancel, onConfirm, deleting }) {
  return <div className="modal-backdrop" role="presentation"><div className="confirm-modal card-surface" role="dialog" aria-modal="true" aria-labelledby="delete-poll-title"><span className="eyebrow">DELETE POLL</span><h2 id="delete-poll-title">Delete this poll?</h2><p>Are you sure you want to delete this poll?</p><p className="settings-note">This action cannot be undone.</p><div className="share-actions"><button className="small-action" type="button" onClick={onCancel} disabled={deleting}>Cancel</button><button className="delete-action" type="button" onClick={() => onConfirm(poll.id)} disabled={deleting}>{deleting ? 'Deleting...' : 'Delete'}</button></div></div></div>;
}

export default function Dashboard() {
  const { logout } = useAuth();
  const [polls, setPolls] = useState([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All'); const [sharePoll, setSharePoll] = useState(null); const [deleteTarget, setDeleteTarget] = useState(null); const [deleting, setDeleting] = useState(false); const [success, setSuccess] = useState('');
  useEffect(() => { getMyPolls().then((response) => setPolls((response.data || []).map((item) => ({ ...item.poll, counts: item.counts, totalVotes: item.totalVotes, status: item.status })))).catch(() => setPolls([])); }, []);
  const visiblePolls = useMemo(() => polls.filter((poll) => { const matchesQuery = poll.question.toLowerCase().includes(query.toLowerCase()) || poll.id.toLowerCase().includes(query.toLowerCase()); return matchesQuery && (status === 'All' || poll.status === status); }), [polls, query, status]);
  const totalVotes = polls.reduce((sum, poll) => sum + Number(poll.totalVotes || 0), 0); const activePolls = polls.filter((poll) => poll.status === 'Active').length;
  const download = async (id) => { const response = await getPollReport(id); const link = document.createElement('a'); link.href = URL.createObjectURL(response.data); link.download = `poll-${id}-report.csv`; link.click(); URL.revokeObjectURL(link.href); };
  const confirmDelete = async (id) => { setDeleting(true); try { await deletePoll(id); setPolls((current) => current.filter((poll) => poll.id !== id)); setDeleteTarget(null); setSuccess('Poll deleted successfully.'); setTimeout(() => setSuccess(''), 2500); } finally { setDeleting(false); } };
  return <main className="dashboard-shell"><CreatorSidebar /><section className="content-panel"><div className="section-heading"><div><span className="eyebrow">MY POLLS</span><h1>Make every question count.</h1></div><Link className="button" to="/create">Create Poll</Link></div>{success && <div className="notice">{success}</div>}<div className="poll-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search your polls..." /><select value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option><option>Active</option><option>Closed</option></select></div><div className="stats-grid"><div className="stat-card"><span>Total Polls</span><strong>{polls.length}</strong></div><div className="stat-card"><span>Total Votes</span><strong>{totalVotes}</strong></div><div className="stat-card"><span>Active Polls</span><strong>{activePolls}</strong></div><div className="stat-card"><span>Closed Polls</span><strong>{polls.length - activePolls}</strong></div></div><div className="poll-list">{visiblePolls.length === 0 && <div className="empty-state card-surface">No polls match this view.</div>}{visiblePolls.map((poll) => <article className="poll-card card-surface" key={poll.id}><div className="poll-card-top"><div><span className="pill">{poll.status}</span><h3>{poll.question}</h3></div><span className="poll-id">ID: {poll.id}</span></div><div className="poll-meta-row"><span>{poll.totalVotes || 0} votes</span><span>{poll.deadlineAt ? new Date(Number(poll.deadlineAt)).toLocaleString() : 'No deadline'}</span></div><div className="card-actions"><Link className="small-action" to={`/results/${poll.id}`}>View Results</Link><Link className="small-action" to={`/polls/${poll.id}/voters`}>View Voters</Link><Link className="small-action" to={`/analytics/${poll.id}`}>Analytics</Link><button className="small-action" type="button" onClick={() => setSharePoll(poll)}>Share</button><button className="small-action" type="button" onClick={() => download(poll.id)}>Download Report</button><button className="delete-icon" type="button" aria-label={`Delete ${poll.question}`} title="Delete poll" onClick={() => setDeleteTarget(poll)}>🗑</button></div></article>)}</div></section>{sharePoll && <ShareDialog poll={sharePoll} onClose={() => setSharePoll(null)} />}{deleteTarget && <DeleteDialog poll={deleteTarget} onCancel={() => setDeleteTarget(null)} onConfirm={confirmDelete} deleting={deleting} />}</main>;
}
